/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6 */

#ifndef PB_PORTAL__PIO_LIBDEPS_USB_ESP32_PORTAL_FRAMEWORK_PROTO_PORTAL_PB_H_INCLUDED
#define PB_PORTAL__PIO_LIBDEPS_USB_ESP32_PORTAL_FRAMEWORK_PROTO_PORTAL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _portal_Skill { 
    portal_Skill_Skill_Default = 0, 
    portal_Skill_Lecive_kouzlo = 1, 
    portal_Skill_Michani_lektvaru = 2, 
    portal_Skill_Kouzlo_sily = 3, 
    portal_Skill_Kouzlo_obratnosti = 4, 
    portal_Skill_Obranne_kouzlo = 5, 
    portal_Skill_Strileni_z_luku = 6, 
    portal_Skill_Kouzlo_penez = 7, 
    portal_Skill_Kouzlo_jidla = 8, 
    portal_Skill_Odemykani_zamku = 9, 
    portal_Skill_Pametove_kouzlo = 10, 
    portal_Skill_Kouzlo_zmenseni = 11, 
    portal_Skill_Hod_sekerou_na_spalek = 12, 
    portal_Skill_Kouzlo_stesti = 13, 
    portal_Skill_Kouzlo_ticha = 14, 
    portal_Skill_Poznavacka_rostlin_a_stromu = 15, 
    portal_Skill_Kouzlo_dychani_pod_vodou = 16, 
    portal_Skill_Kouzlo_videni_do_budoucnosti = 17, 
    portal_Skill_Poznavacka_zvirat = 18, 
    portal_Skill_Kouzlo_neviditelnosti = 19, 
    portal_Skill_Kouzlo_zrychleni = 20, 
    portal_Skill_Plavani = 21, 
    portal_Skill_Skutecne_videni = 22, 
    portal_Skill_Kouzlo_zpomaleni_casu = 23, 
    portal_Skill_Vareni = 24, 
    portal_Skill_Kouzlo_svetla = 25, 
    portal_Skill_Kouzlo_mapovani_oblasti = 26, 
    portal_Skill_Kouzlo_nadbytku = 27, 
    portal_Skill_Kouzlo_teleportace = 28, 
    portal_Skill_Sifry = 29, 
    portal_Skill_Kouzlo_odvahy = 30, 
    portal_Skill_Rozdelani_ohne = 31, 
    portal_Skill_Lezeni_po_skalach = 32 
} portal_Skill;

/* Struct definitions */
typedef struct _portal_PlayerData { 
    char secret[8];
    uint32_t user_id;
    uint32_t strength;
    uint32_t magic;
    uint32_t dexterity;
    uint32_t bonus_points;
    pb_size_t skills_count;
    portal_Skill skills[40];
} portal_PlayerData;


/* Helper constants for enums */
#define _portal_Skill_MIN portal_Skill_Skill_Default
#define _portal_Skill_MAX portal_Skill_Lezeni_po_skalach
#define _portal_Skill_ARRAYSIZE ((portal_Skill)(portal_Skill_Lezeni_po_skalach+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define portal_PlayerData_init_default           {"", 0, 0, 0, 0, 0, 0, {_portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN}}
#define portal_PlayerData_init_zero              {"", 0, 0, 0, 0, 0, 0, {_portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN, _portal_Skill_MIN}}

/* Field tags (for use in manual encoding/decoding) */
#define portal_PlayerData_secret_tag             1
#define portal_PlayerData_user_id_tag            2
#define portal_PlayerData_strength_tag           3
#define portal_PlayerData_magic_tag              4
#define portal_PlayerData_dexterity_tag          5
#define portal_PlayerData_bonus_points_tag       6
#define portal_PlayerData_skills_tag             10

/* Struct field encoding specification for nanopb */
#define portal_PlayerData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   secret,            1) \
X(a, STATIC,   REQUIRED, UINT32,   user_id,           2) \
X(a, STATIC,   REQUIRED, UINT32,   strength,          3) \
X(a, STATIC,   REQUIRED, UINT32,   magic,             4) \
X(a, STATIC,   REQUIRED, UINT32,   dexterity,         5) \
X(a, STATIC,   REQUIRED, UINT32,   bonus_points,      6) \
X(a, STATIC,   REPEATED, UENUM,    skills,           10)
#define portal_PlayerData_CALLBACK NULL
#define portal_PlayerData_DEFAULT NULL

extern const pb_msgdesc_t portal_PlayerData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define portal_PlayerData_fields &portal_PlayerData_msg

/* Maximum encoded size of messages (where known) */
#define portal_PlayerData_size                   119

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
