/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_PORTAL_PORTAL_PB_H_INCLUDED
#define PB_PORTAL_PORTAL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _portal_PlayerData { 
    char secret[8]; 
    uint32_t user_id; 
    uint32_t strength; 
    uint32_t magic; 
    uint32_t dexterity; 
} portal_PlayerData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define portal_PlayerData_init_default           {"", 0, 0, 0, 0}
#define portal_PlayerData_init_zero              {"", 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define portal_PlayerData_secret_tag             1
#define portal_PlayerData_user_id_tag            2
#define portal_PlayerData_strength_tag           3
#define portal_PlayerData_magic_tag              4
#define portal_PlayerData_dexterity_tag          5

/* Struct field encoding specification for nanopb */
#define portal_PlayerData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   secret,            1) \
X(a, STATIC,   REQUIRED, UINT32,   user_id,           2) \
X(a, STATIC,   REQUIRED, UINT32,   strength,          3) \
X(a, STATIC,   REQUIRED, UINT32,   magic,             4) \
X(a, STATIC,   REQUIRED, UINT32,   dexterity,         5)
#define portal_PlayerData_CALLBACK NULL
#define portal_PlayerData_DEFAULT NULL

extern const pb_msgdesc_t portal_PlayerData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define portal_PlayerData_fields &portal_PlayerData_msg

/* Maximum encoded size of messages (where known) */
#define portal_PlayerData_size                   33

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
